//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBloggy.Domain.Entities
{
    using GenericRepository;
    using System;
    using System.Collections.Generic;
    
    public partial class Author : IEntity<Guid>
    {
        public Author()
        {
            this.BlogPosts = new HashSet<BlogPost>();
            this.DynamicPages = new HashSet<DynamicPage>();
        }
    
        public System.Guid Id { get; set; }
        public string AuthorName { get; set; }
        public string AuthorSurname { get; set; }
        public string TwitterHandle { get; set; }
        public string CreationIp { get; set; }
        public System.DateTimeOffset CreatedOn { get; set; }
        public string LastUpdateIp { get; set; }
        public Nullable<System.DateTimeOffset> LastUpdatedOn { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<BlogPost> BlogPosts { get; set; }
        public virtual ICollection<DynamicPage> DynamicPages { get; set; }
    }
}
