//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBloggy.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogRoll : IEntity
    {
        public System.Guid Key { get; set; }
        public System.Guid LanguageKey { get; set; }
        public string BlogName { get; set; }
        public string BlogAuthor { get; set; }
        public string BlogUrl { get; set; }
        public string FeedUrl { get; set; }
        public Nullable<int> Order { get; set; }
        public bool IsApproved { get; set; }
        public string CreationIp { get; set; }
        public System.DateTimeOffset CreatedOn { get; set; }
        public string LastUpdateIp { get; set; }
        public Nullable<System.DateTimeOffset> LastUpdatedOn { get; set; }
    
        public virtual Language Language { get; set; }
    }
}
