//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBloggy.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPost : IEntity
    {
        public BlogPost()
        {
            this.BlogPostComments = new HashSet<BlogPostComment>();
            this.BlogPostUrls = new HashSet<BlogPostUrl>();
            this.TagsForBlogPosts = new HashSet<TagsForBlogPost>();
        }
    
        public System.Guid Key { get; set; }
        public System.Guid LanguageKey { get; set; }
        public Nullable<int> SecondaryKey { get; set; }
        public string Title { get; set; }
        public string BriefInfo { get; set; }
        public string Content { get; set; }
        public string ImagePath { get; set; }
        public bool IsApproved { get; set; }
        public string CreationIp { get; set; }
        public System.DateTimeOffset CreatedOn { get; set; }
        public string LastUpdateIp { get; set; }
        public Nullable<System.DateTimeOffset> LastUpdatedOn { get; set; }
    
        public virtual ICollection<BlogPostComment> BlogPostComments { get; set; }
        public virtual Language Language { get; set; }
        public virtual ICollection<BlogPostUrl> BlogPostUrls { get; set; }
        public virtual ICollection<TagsForBlogPost> TagsForBlogPosts { get; set; }
    }
}
