//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBloggy.Domain.Entities
{
    using GenericRepository;
    using System;
    using System.Collections.Generic;
    
    public partial class DynamicPage : IEntity<Guid>
    {
        public DynamicPage()
        {
            this.TagsForDynamicPages = new HashSet<TagsForDynamicPage>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid LanguageId { get; set; }
        public System.Guid AuthorId { get; set; }
        public string Title { get; set; }
        public string BriefInfo { get; set; }
        public string Content { get; set; }
        public bool IsApproved { get; set; }
        public string CreationIp { get; set; }
        public System.DateTimeOffset CreatedOn { get; set; }
        public string LastUpdateIp { get; set; }
        public Nullable<System.DateTimeOffset> LastUpdatedOn { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Language Language { get; set; }
        public virtual ICollection<TagsForDynamicPage> TagsForDynamicPages { get; set; }
    }
}
