//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBloggy.Domain.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagsForDynamicPage
    {
        public int TagsForDynamicPageId { get; set; }
        public int DynamicPageId { get; set; }
        public int TagId { get; set; }
    
        public virtual DynamicPage DynamicPage { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
