#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBloggy.Web.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.Configuration;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcBloggy.Resources;
    using MvcBloggy.Web.Application.Resources;
    using MvcBloggy.Web.Application.Utility;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_CultureSwitcher.cshtml")]
    public class _CultureSwitcher : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _CultureSwitcher()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Views\Shared\_CultureSwitcher.cshtml"
  
    Dictionary<string, object> routeValues = new Dictionary<string, object>();
    
    foreach (var item in ViewContext.RouteData.Values.Where(x => x.Key != "language")) {
        routeValues.Add(item.Key, item.Value);
    }
    routeValues.Add("language", string.Empty);
    
    RouteValueDictionary routeValueDic = new RouteValueDictionary(
        routeValues
    );

    var appLanguages = MvcBloggy.Web.Application.Utility.AppLanguage.GetAllBut(System.Threading.Thread.CurrentThread.CurrentUICulture.TwoLetterISOLanguageName);


            
            #line default
            #line hidden

            
            #line 15 "..\..\Views\Shared\_CultureSwitcher.cshtml"
 if (appLanguages.Count() >= 1) { 

            
            #line default
            #line hidden
WriteLiteral("<div id=\"culture-switcher\">\r\n");


            
            #line 17 "..\..\Views\Shared\_CultureSwitcher.cshtml"
 foreach (var language in appLanguages) {
    routeValueDic["language"] = language;

            
            #line default
            #line hidden
WriteLiteral("    <a href=\"");


            
            #line 19 "..\..\Views\Shared\_CultureSwitcher.cshtml"
        Write(Url.RouteUrl(routeValueDic));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n        <img src=\"");


            
            #line 20 "..\..\Views\Shared\_CultureSwitcher.cshtml"
             Write(Url.Content(string.Format("~/content/v2/icons/flags/{0}.png", language)));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"");


            
            #line 20 "..\..\Views\Shared\_CultureSwitcher.cshtml"
                                                                                             Write(language);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n    </a>\r\n");


            
            #line 22 "..\..\Views\Shared\_CultureSwitcher.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");


            
            #line 24 "..\..\Views\Shared\_CultureSwitcher.cshtml"
}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
