#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBloggy.Web.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.Configuration;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcBloggy.Resources;
    using MvcBloggy.Web.Application.Resources;
    using MvcBloggy.Web.Application.Utility;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public class _Layout : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Layout()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<!--[if lt IE 7]> <html class=\"no-js ie6 oldie\" lang=\"");


            
            #line 2 "..\..\Views\Shared\_Layout.cshtml"
                                                 Write(System.Threading.Thread.CurrentThread.CurrentUICulture.TwoLetterISOLanguageName);

            
            #line default
            #line hidden
WriteLiteral("\"> <![endif]-->\r\n<!--[if IE 7]>    <html class=\"no-js ie7 oldie\" lang=\"");


            
            #line 3 "..\..\Views\Shared\_Layout.cshtml"
                                                 Write(System.Threading.Thread.CurrentThread.CurrentUICulture.TwoLetterISOLanguageName);

            
            #line default
            #line hidden
WriteLiteral("\"> <![endif]-->\r\n<!--[if IE 8]>    <html class=\"no-js ie8 oldie\" lang=\"");


            
            #line 4 "..\..\Views\Shared\_Layout.cshtml"
                                                 Write(System.Threading.Thread.CurrentThread.CurrentUICulture.TwoLetterISOLanguageName);

            
            #line default
            #line hidden
WriteLiteral("\"> <![endif]-->\r\n<!--[if gt IE 8]><!--> <html class=\"no-js\" lang=\"");


            
            #line 5 "..\..\Views\Shared\_Layout.cshtml"
                                            Write(System.Threading.Thread.CurrentThread.CurrentUICulture.TwoLetterISOLanguageName);

            
            #line default
            #line hidden
WriteLiteral("\"> <!--<![endif]-->\r\n<head>\r\n    <meta charset=\"utf-8\">\r\n    <title>");


            
            #line 8 "..\..\Views\Shared\_Layout.cshtml"
       Write((!string.IsNullOrEmpty(ViewBag.Title)) ? ViewBag.Title + " - " + ConfigurationManager.AppSettings["MainPageTitleStructure"] : System.Configuration.ConfigurationManager.AppSettings["MainPageTitleStructure"]);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n");


            
            #line 9 "..\..\Views\Shared\_Layout.cshtml"
     if (!string.IsNullOrEmpty(ViewBag.MeteDescription)){
            
            #line default
            #line hidden
WriteLiteral("<meta name=\"description\" content=\"");


            
            #line 9 "..\..\Views\Shared\_Layout.cshtml"
                                                                                            Write(ViewBag.MetaDescription);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 9 "..\..\Views\Shared\_Layout.cshtml"
                                                                                                                                  }

            
            #line default
            #line hidden

            
            #line 10 "..\..\Views\Shared\_Layout.cshtml"
     if (!string.IsNullOrEmpty(ViewBag.MeteKeyword)){
            
            #line default
            #line hidden
WriteLiteral("<meta name=\"keyword\" content=\"");


            
            #line 10 "..\..\Views\Shared\_Layout.cshtml"
                                                                                    Write(ViewBag.MetaKeyword);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 10 "..\..\Views\Shared\_Layout.cshtml"
                                                                                                                      }

            
            #line default
            #line hidden

            
            #line 11 "..\..\Views\Shared\_Layout.cshtml"
     if (!string.IsNullOrEmpty(ViewBag.Canonical)){
            
            #line default
            #line hidden
WriteLiteral("<link rel=\"canonical\" href=\"");


            
            #line 11 "..\..\Views\Shared\_Layout.cshtml"
                                                                                Write(ViewBag.Canonical);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 11 "..\..\Views\Shared\_Layout.cshtml"
                                                                                                                }

            
            #line default
            #line hidden
WriteLiteral("    \r\n    <meta name=\"author\" content=\"");


            
            #line 13 "..\..\Views\Shared\_Layout.cshtml"
                            Write(ConfigurationManager.AppSettings["WebSiteAuthor"]);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n    <meta name=\"viewport\" content=\"width=device-width,initial-scale=1\">\r\n    " +
"<link href=\"");


            
            #line 15 "..\..\Views\Shared\_Layout.cshtml"
           Write(Microsoft.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl(string.Format("~/themes/{0}/globalcss", ConfigurationManager.AppSettings["AppDefaultTheme"])));

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"stylesheet\" />\r\n    <script src=\"");


            
            #line 16 "..\..\Views\Shared\_Layout.cshtml"
            Write(Microsoft.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/scripts/v2/modernizr"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n    <!--[if lt IE 9]>\r\n    <script src=\"");


            
            #line 18 "..\..\Views\Shared\_Layout.cshtml"
            Write(Url.Content("~/scripts/respond/respond.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n    <![endif]-->\r\n    ");


            
            #line 20 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("head", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n\r\n<body itemscope itemtype=\"http://schema.org/WebPage\">\r\n    <div id=\"" +
"mvcbloggy-wrapper\">\r\n        <header>\r\n            <section id=\"header-left\">\r\n " +
"               ");


            
            #line 27 "..\..\Views\Shared\_Layout.cshtml"
           Write(Html.Partial("LayoutHeaderLeft"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </section>\r\n            <section id=\"header-right\">\r\n              " +
"  ");


            
            #line 30 "..\..\Views\Shared\_Layout.cshtml"
           Write(Html.Partial("LayoutHeaderRight"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </section>\r\n            <div class=\"clearfix\"></div>\r\n            <" +
"nav>\r\n                <ul>\r\n                    <li class=\"mvcbloggy-current\">");


            
            #line 35 "..\..\Views\Shared\_Layout.cshtml"
                                             Write(Html.ActionLink(Strings.Home, "index", new { controller = "default", area = string.Empty }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                    <li>");


            
            #line 36 "..\..\Views\Shared\_Layout.cshtml"
                   Write(Html.ActionLink(Strings.Archive, "index", new { controller = "archive", area = string.Empty }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                    <li>");


            
            #line 37 "..\..\Views\Shared\_Layout.cshtml"
                   Write(Html.ActionLink(Strings.AboutMe, "index", new { controller = "dynamicPage", page = "about", area = string.Empty }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                    <li>");


            
            #line 38 "..\..\Views\Shared\_Layout.cshtml"
                   Write(Html.ActionLink(Strings.ContactMe, "index", new { controller = "contact", area = string.Empty }));

            
            #line default
            #line hidden
WriteLiteral("</li>\r\n                </ul>\r\n            </nav>\r\n            <div class=\"clearfi" +
"x\"></div>\r\n        </header>\r\n        <div id=\"mvcbloggy-innerwrapper\">\r\n       " +
"     <div id=\"sidebar\"></div>\r\n            <div id=\"mainbar\">\r\n                ");


            
            #line 46 "..\..\Views\Shared\_Layout.cshtml"
           Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n            <div class=\"clearfix\"></div>\r\n        </div>\r\n " +
"       <footer>\r\n            ");


            
            #line 51 "..\..\Views\Shared\_Layout.cshtml"
       Write(Html.Partial("LayoutFooter"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </footer>\r\n    </div>\r\n    <script src=\"//ajax.googleapis.com/ajax/libs" +
"/jquery/1.7.0/jquery.min.js\"></script>\r\n    <script>window.jQuery || document.wr" +
"ite(\'<script src=\"scripts/jquery-1.7.min.js\"><\\/script>\')</script>\r\n    <script " +
"src=\"");


            
            #line 56 "..\..\Views\Shared\_Layout.cshtml"
            Write(Microsoft.Web.Optimization.BundleTable.Bundles.ResolveBundleUrl("~/scripts/v2/globaljs"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n    ");


            
            #line 57 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("scripts", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 58 "..\..\Views\Shared\_Layout.cshtml"
Write(MvcMiniProfiler.MiniProfiler.RenderIncludes());

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");



WriteLiteral("\r\n\r\n  <!--[if lt IE 7 ]>\r\n    <script src=\"//ajax.googleapis.com/ajax/libs/chrome" +
"-frame/1.0.3/CFInstall.min.js\"></script>\r\n    <script>window.attachEvent(\'onload" +
"\',function(){CFInstall.check({mode:\'overlay\'})})</script>\r\n  <![endif]-->\r\n</bod" +
"y>\r\n</html>");


        }
    }
}
#pragma warning restore 1591
