#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBloggy.Web.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.Configuration;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MvcBloggy.Resources;
    using MvcBloggy.Web.Application.Resources;
    using MvcBloggy.Web.Application.Utility;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/LayoutHeaderRight.cshtml")]
    public class LayoutHeaderRight : System.Web.Mvc.WebViewPage<dynamic>
    {
        public LayoutHeaderRight()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div id=\"mvcbloggy-cultureswitcher\">\r\n    ");


            
            #line 2 "..\..\Views\Shared\LayoutHeaderRight.cshtml"
Write(Html.Partial("_CultureSwitcher"));

            
            #line default
            #line hidden
WriteLiteral(@"
</div>
<table id=""mvcbloggy-feedburner"">
    <tbody>
        <tr>
            <td>
            <a target=""_blank"" class=""no-border-img-link"" href=""http://feeds.feedburner.com/TugberkUgurlu"">
                <img alt=""rss"" title=""Subscribe Rss Feed !"" src=""http://www.tugberkugurlu.com/Content/App_Icons/icon-feed-28x28.png"" />
            </a>
            </td>
            <td>
            <a target=""_blank"" href=""http://feeds.feedburner.com/tugberkugurlu"">
                <img src=""http://feeds.feedburner.com/~fc/TugberkUgurlu?bg=FF6600&amp;fg=FFFFFF&amp;anim=1"" height=""26"" width=""88"" style=""border:0"" alt="""" />
            </a>
            </td>
        </tr>
    </tbody>
</table>");


        }
    }
}
#pragma warning restore 1591
