#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17020
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBloggy.Web.Areas.Admin.Views.Default
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.2.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Default/Index.cshtml")]
    public class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {

            
            #line 1 "..\..\Areas\Admin\Views\Default\Index.cshtml"
  
    ViewBag.Title = "Index";


            
            #line default
            #line hidden
WriteLiteral("\r\n<!-- Main hero unit for a primary marketing message or call to action -->\r\n<div" +
" class=\"hero-unit\">\r\n    <h1>Hello, world!</h1>\r\n    <p>Vestibulum id ligula por" +
"ta felis euismod semper. Integer posuere erat a ante venenatis dapibus posuere v" +
"elit aliquet. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, e" +
"get lacinia odio sem nec elit.</p>\r\n    <p><a class=\"btn primary large\">Learn mo" +
"re &raquo;</a></p>\r\n</div>\r\n\r\n<!-- Example row of columns -->\r\n<div class=\"row\">" +
"\r\n    <div class=\"span6\">\r\n    <h2>Heading</h2>\r\n    <p>Etiam porta sem malesuad" +
"a magna mollis euismod. Integer posuere erat a ante venenatis dapibus posuere ve" +
"lit aliquet. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis " +
"vestibulum. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, ege" +
"t lacinia odio sem nec elit.</p>\r\n    <p><a class=\"btn\" href=\"#\">View details &r" +
"aquo;</a></p>\r\n    </div>\r\n    <div class=\"span5\">\r\n    <h2>Heading</h2>\r\n      " +
"  <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac " +
"cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit ame" +
"t risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p" +
">\r\n    <p><a class=\"btn\" href=\"#\">View details &raquo;</a></p>\r\n    </div>\r\n    " +
"<div class=\"span5\">\r\n    <h2>Heading</h2>\r\n    <p>Donec sed odio dui. Cras justo" +
" odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta fe" +
"lis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condi" +
"mentum nibh, ut fermentum massa justo sit amet risus.</p>\r\n    <p><a class=\"btn\"" +
" href=\"#\">View details &raquo;</a></p>\r\n    </div>\r\n</div>\r\n\r\n<hr>\r\n\r\n<!-- Examp" +
"le row of columns -->\r\n<div class=\"row\">\r\n    <div class=\"span6\">\r\n    <h2>Headi" +
"ng</h2>\r\n    <p>Etiam porta sem malesuada magna mollis euismod. Integer posuere " +
"erat a ante venenatis dapibus posuere velit aliquet. Aenean eu leo quam. Pellent" +
"esque ornare sem lacinia quam venenatis vestibulum. Duis mollis, est non commodo" +
" luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.</p>\r\n    <p" +
"><a class=\"btn\" href=\"#\">View details &raquo;</a></p>\r\n    </div>\r\n    <div clas" +
"s=\"span5\">\r\n    <h2>Heading</h2>\r\n        <p>Donec id elit non mi porta gravida " +
"at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentu" +
"m nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna" +
" mollis euismod. Donec sed odio dui. </p>\r\n    <p><a class=\"btn\" href=\"#\">View d" +
"etails &raquo;</a></p>\r\n    </div>\r\n    <div class=\"span5\">\r\n    <h2>Heading</h2" +
">\r\n    <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas " +
"eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellu" +
"s ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo si" +
"t amet risus.</p>\r\n    <p><a class=\"btn\" href=\"#\">View details &raquo;</a></p>\r\n" +
"    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
