//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MvcBloggy.Data.DataAccess.SqlServer
{
    public partial class BlogPost
    {
        public BlogPost()
        {
            this.BlogPostComments = new HashSet<BlogPostComment>();
            this.Tags = new HashSet<Tag>();
        }
    
        public int BlogPostId { get; set; }
        public int LanguageId { get; set; }
        public Nullable<int> SecondaryID { get; set; }
        public string Title { get; set; }
        public string BriefInfo { get; set; }
        public string Content { get; set; }
        public string ImagePath { get; set; }
        public bool IsApproved { get; set; }
        public string CreationIp { get; set; }
        public Nullable<System.DateTimeOffset> CreatedOn { get; set; }
        public Nullable<System.DateTimeOffset> LastUpdatedOn { get; set; }
    
        public virtual ICollection<BlogPostComment> BlogPostComments { get; set; }
        public virtual Language Language { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
    }
    
}
