//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MvcBloggy.Data.DataAccess.SqlServer
{
    public partial class BlogPostComment
    {
        public int BlogCommentID { get; set; }
        public int BlogPostID { get; set; }
        public string CommenterName { get; set; }
        public string CommenterEmail { get; set; }
        public string CommenterWebSite { get; set; }
        public string CommenterAuthType { get; set; }
        public bool IsAuthor { get; set; }
        public string CommentSubject { get; set; }
        public string CommentContent { get; set; }
        public System.DateTimeOffset CreatedOn { get; set; }
        public string CreationIp { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual BlogPost BlogPost { get; set; }
    }
    
}
