//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MvcBloggy.Data.DataAccess.SqlServer
{
    public partial class BlogPost
    {
        public BlogPost()
        {
            this.BlogPostComments = new HashSet<BlogPostComment>();
        }
    
        public int BlogPostID { get; set; }
        public int LanguageID { get; set; }
        public System.Guid BlogPostGUID { get; set; }
        public Nullable<int> SecondaryID { get; set; }
        public string BlogPostTitle { get; set; }
        public string BlogPostBriefInfo { get; set; }
        public string BlogPostContent { get; set; }
        public string BlogPostTags { get; set; }
        public string BlogPostImagePath { get; set; }
        public string CreationIp { get; set; }
        public Nullable<System.DateTimeOffset> CreatedOn { get; set; }
        public Nullable<System.DateTimeOffset> LastUpdatedOn { get; set; }
        public bool IsApproved { get; set; }
    
        public virtual ICollection<BlogPostComment> BlogPostComments { get; set; }
        public virtual Language Language { get; set; }
    }
    
}
