//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBloggy.Data.DataAccess.SqlServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlogPostComment
    {
        public int BlogCommentID { get; set; }
        public int BlogPostID { get; set; }
        public Nullable<System.Guid> BlogCommentGUID { get; set; }
        public string CommenterName { get; set; }
        public string CommenterEmail { get; set; }
        public string CommenterWebSite { get; set; }
        public string CommenterAuthType { get; set; }
        public Nullable<bool> IsAuthor { get; set; }
        public string CommentSubject { get; set; }
        public string CommentContent { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreationIp { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    
        public virtual BlogPost BlogPost { get; set; }
    }
}
