//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MvcBloggy.Data.DataAccess.SqlServer
{
    public partial class DynamicPage
    {
        public int DynamicPageID { get; set; }
        public int LanguageID { get; set; }
        public string PageTitle { get; set; }
        public string PageBriefInfo { get; set; }
        public string PageContent { get; set; }
        public bool IsApproved { get; set; }
        public Nullable<System.DateTimeOffset> CreatedOn { get; set; }
        public Nullable<System.DateTimeOffset> LastUpdatedOn { get; set; }
    
        public virtual Language Language { get; set; }
    }
    
}
