//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcBloggy.Data.DataAccess.SqlServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class RestrictedPageName
    {
        public int RestrictedPageNameId { get; set; }
        public int LanguageId { get; set; }
        public string Term { get; set; }
        public Nullable<System.DateTimeOffset> CreatedOn { get; set; }
    
        public virtual Language Language { get; set; }
    }
}
