//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MvcBloggy.Data.DataAccess.SqlServer
{
    public partial class Tag
    {
        public int TagId { get; set; }
        public int BlogPostId { get; set; }
        public string TagName { get; set; }
    
        public virtual BlogPost BlogPost { get; set; }
    }
    
}
