CREATE TABLE [dbo].[Authors] (
	[Id] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
	[AuthorName] NVARCHAR(50) NOT NULL,
	[AuthorSurname] NVARCHAR(50) NOT NULL,
	[TwitterHandle] NVARCHAR(50) NOT NULL,
	[CreationIp] NVARCHAR(50) NULL,
	[CreatedOn] DATETIMEOFFSET NOT NULL,
	[LastUpdateIp] NVARCHAR(50) NULL,
	[LastUpdatedOn] DATETIMEOFFSET NULL,
	CONSTRAINT [PK_Authors] PRIMARY KEY CLUSTERED ([Id])
);