CREATE TABLE [dbo].[BlogPostComments] (
	[Key] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
	[BlogPostKey] UNIQUEIDENTIFIER NOT NULL,
	[Name] NVARCHAR(300) NOT NULL,
	[Email] NVARCHAR(300) NOT NULL,
	[WebSite] NVARCHAR(300) NULL,
	[AuthProvider] NVARCHAR(300) NULL,
	[IsByAuthor] BIT NOT NULL,
	[Subject] NVARCHAR(300) NULL,
	[Content] NVARCHAR(MAX) NULL,
	[IsMarkedAsSpam] BIT NOT NULL,
	[IsApproved] BIT NOT NULL,
	[CreationIp] NVARCHAR(50) NULL,
	[CreatedOn] DATETIMEOFFSET NOT NULL,
	[LastUpdateIp] NVARCHAR(50) NULL,
	[LastUpdatedOn] DATETIMEOFFSET NULL,
	CONSTRAINT [PK_BlogPostComments] PRIMARY KEY ([Key])
);