CREATE TABLE [dbo].[Tags] (
	[TagId] INT IDENTITY NOT NULL,
	[LanguageId] INT NOT NULL,
	[TagName] NVARCHAR(100) NOT NULL,
	[CreationIp] NVARCHAR(50) NULL,
	[CreatedOn] DATETIMEOFFSET NOT NULL,
    CONSTRAINT [PK_Tags] PRIMARY KEY ([TagId])
);