CREATE TABLE [dbo].[TagsForBlogPosts] (
	[Key] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
	[BlogPostKey] UNIQUEIDENTIFIER NOT NULL,
	[TagKey] UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT [PK_TagsForBlogPosts] PRIMARY KEY ([Key])
);