CREATE TABLE [dbo].[Tags] (
	[Key] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWSEQUENTIALID(),
	[LanguageKey] UNIQUEIDENTIFIER NOT NULL,
	[TagName] NVARCHAR(100) NOT NULL,
	[CreationIp] NVARCHAR(50) NULL,
	[CreatedOn] DATETIMEOFFSET NOT NULL,
    CONSTRAINT [PK_Tags] PRIMARY KEY ([Key])
);